// Auto-generated by: bun run generate:color-token
// Source: global.css (oklch converted to rgb for React Native compatibility)

export const LIGHT_COLORS = {
  background: 'rgb(253, 253, 253)',
  foreground: 'rgb(250, 250, 250)',
  card: 'rgb(24, 24, 27)',
  cardForeground: 'rgb(250, 250, 250)',
  popover: 'rgb(24, 24, 27)',
  popoverForeground: 'rgb(250, 250, 250)',
  primary: 'rgb(142, 81, 255)',
  primaryForeground: 'rgb(245, 243, 255)',
  secondary: 'rgb(39, 39, 42)',
  secondaryForeground: 'rgb(250, 250, 250)',
  muted: 'rgb(39, 39, 42)',
  mutedForeground: 'rgb(159, 159, 169)',
  accent: 'rgb(39, 39, 42)',
  accentForeground: 'rgb(250, 250, 250)',
  destructive: 'rgb(255, 100, 103)',
  destructiveForeground: 'rgb(255, 255, 255)',
  border: 'rgba(255, 255, 255, 0.1)',
  input: 'rgba(255, 255, 255, 0.15)',
  ring: 'rgb(77, 23, 154)',
} as const

export const DARK_COLORS = {
  background: 'rgb(9, 9, 11)',
  foreground: 'rgb(250, 250, 250)',
  card: 'rgb(24, 24, 27)',
  cardForeground: 'rgb(250, 250, 250)',
  popover: 'rgb(24, 24, 27)',
  popoverForeground: 'rgb(250, 250, 250)',
  primary: 'rgb(142, 81, 255)',
  primaryForeground: 'rgb(245, 243, 255)',
  secondary: 'rgb(39, 39, 42)',
  secondaryForeground: 'rgb(250, 250, 250)',
  muted: 'rgb(39, 39, 42)',
  mutedForeground: 'rgb(159, 159, 169)',
  accent: 'rgb(39, 39, 42)',
  accentForeground: 'rgb(250, 250, 250)',
  destructive: 'rgb(255, 100, 103)',
  destructiveForeground: 'rgb(255, 255, 255)',
  border: 'rgba(255, 255, 255, 0.1)',
  input: 'rgba(255, 255, 255, 0.15)',
  ring: 'rgb(77, 23, 154)',
} as const

export type ColorToken = keyof typeof LIGHT_COLORS
