const fs = require('node:fs')
const path = require('node:path')

const cssContent = fs.readFileSync('./global.css', 'utf8')

const rootVariablesRegex = /:root\s*{[^}]*}/
const darkRootVariablesRegex = /.dark:root\s*{[^}]*}/

const rootMatch = cssContent.match(rootVariablesRegex)
const darkRootMatch = cssContent.match(darkRootVariablesRegex)

const parseVariables = (block) => {
  const variables = {}
  block
    .slice(block.indexOf('{') + 1, block.indexOf('}'))
    .split(';')
    .forEach((prop) => {
      const [key, value] = prop.split(':').map((part) => part.trim())
      if (key && value) {
        variables[key] = value
      }
    })
  return variables
}

function convertCssVariableName(key) {
  let newKey = key.replace(/^--/, '')

  newKey = newKey.replace(/-([a-z])/g, (match, letter) => letter.toUpperCase())

  return newKey
}

const hslRegex = /^([\d\.]+) ([\d\.]+)% ([\d\.]+)%$/

function isHSLValue(value) {
  return hslRegex.test(value)
}

const formatForReactNative = (variables) => {
  return Object.entries(variables)
    .map(([key, value]) => {
      if (!isHSLValue(value)) return ''
      return `  ${convertCssVariableName(key)}: 'hsl(${value})',`
    })
    .join('\n')
}

const rootVariables = parseVariables(rootMatch[0])
const darkRootVariables = parseVariables(darkRootMatch[0])

const colorTsContent = `
// pnpm run generate:color-token  Generated by script from global.css

export const LIGHT_COLORS = {${formatForReactNative(rootVariables)}} as const
export const DARK_COLORS = {${formatForReactNative(darkRootVariables)}} as const
`

const tsFilePath = path.join('./', 'constant', 'color.ts')
fs.writeFileSync(tsFilePath, colorTsContent, 'utf8')

console.log('React Native color constants have been saved to constant/color.ts')
